# Import de numpy

In [1]:
import numpy as np

### Création d'une matrice

In [75]:
matrix5_6 = np.random.rand(5,6)

### Nombre d'éléments

In [23]:
matrix5_6

array([[0.76381022, 0.03251199, 0.28103769, 0.03850684, 0.73361457,
        0.07349255],
       [0.60107247, 0.49928665, 0.92116329, 0.13834637, 0.72701492,
        0.69676597],
       [0.85046257, 0.01549592, 0.04067199, 0.99412804, 0.58214594,
        0.34328579],
       [0.45427608, 0.40518155, 0.13230691, 0.60293139, 0.51797055,
        0.35329213],
       [0.8581879 , 0.52778616, 0.1380477 , 0.88358698, 0.78424257,
        0.44011557]])

In [28]:
matrix5_6.size # ou np.size(matrix5_6)

30

In [34]:
print("le nombre de colonnes est de " + str(np.size(matrix5_6,1)) +  " et le nombre de lignes est de " + str(np.size(matrix5_6,0)))

le nombre de colonnes est de 6 et le nombre de lignes est de 5


In [76]:
matrix5_6.shape

(5, 6)

### Slice des np.array

In [38]:
vec20 = np.random.rand(20)

In [43]:
vec20

array([0.82841466, 0.93543406, 0.71986524, 0.45832093, 0.14692175,
       0.86801651, 0.05839878, 0.49231329, 0.08622817, 0.73232602,
       0.93429205, 0.28442524, 0.39585617, 0.12146876, 0.28754251,
       0.94888128, 0.92166475, 0.08962932, 0.78498892, 0.05637487])

In [39]:
vec20.size

20

In [42]:
vec20[:10] # les 10 premiers éléments

array([0.82841466, 0.93543406, 0.71986524, 0.45832093, 0.14692175,
       0.86801651, 0.05839878, 0.49231329, 0.08622817, 0.73232602])

In [98]:
vec20[-1:] # dernier élément

array([0.05637487])

In [100]:
vec20[:1] # premier élément

array([0.82841466])

# Opérations sur les matrices 

In [82]:
matrix = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8 ,9 ,10]])

In [83]:
matrix2 = np.array([[10, 20, 30, 40, 50],
                 [60, 70, 80 ,90 ,100]])

In [95]:
matrix3 = np.array([[1, 2, 3, 4],
                 [6, 7, 8 ,9]])

### Addition

In [84]:
matrix + matrix2 

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 110]])

In [96]:
matrix + matrix3

ValueError: operands could not be broadcast together with shapes (2,5) (2,4) 

### Multiplication ( élément par élément)

In [92]:
matrix * matrix2

array([[  10,   40,   90,  160,  250],
       [ 360,  490,  640,  810, 1000]])

In [94]:
matrix3 * matrix

ValueError: operands could not be broadcast together with shapes (2,4) (2,5) 

In [87]:
# Impossible car shape différente

### Produit matricielle  

In [60]:
np.shape(matrix)

(2, 5)

In [61]:
np.shape(matrix2)

(2, 5)

In [88]:
#  Donc produit matricielle impossible entre matrix et matrix2 

In [109]:
np.matmul(matrix2,matrix)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

In [91]:
np.shape(matrix2.T) # On transpose la matrice

(5, 2)

In [110]:
np.matmul(matrix2,matrix.T)

array([[ 550, 1300],
       [1300, 3300]])

# Manipulation de matrices

In [106]:
matrixFlatten = matrix.flatten()

In [107]:
matrix2Flatten = matrix2.flatten()

In [108]:
 np.column_stack((matrixFlatten, matrix2Flatten))

array([[  1,  10],
       [  2,  20],
       [  3,  30],
       [  4,  40],
       [  5,  50],
       [  6,  60],
       [  7,  70],
       [  8,  80],
       [  9,  90],
       [ 10, 100]])